name: Build on Push

on:
  - push

jobs:
  mvn:
    uses: TaurMorchant/workflows-test/.github/workflows/maven-build.yaml@main
    with:
      maven-goal: install
      java-version: 17
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}