name: Build on Push

on:
  - push

jobs:
  mvn:
    uses: TaurMorchant/workflows-test/.github/workflows/run-maven-with-sonar.yaml@main
    with:
      maven-goal: deploy
      java-version: 17
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}