name: Build on Push

on:
  - push

jobs:
  mvn:
    uses: TaurMorchant/workflows-test/.github/workflows/run-maven-with-sonar.yaml@v1.0.0
    with:
      maven-goal: install
      java-version: 17
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}